services:
  mysql:
    image: mysql:8.1
    container_name: inventory-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
